steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/ui-portal:latest',
      '--build-arg', 'PORT=8080',
      '.'
    ]
    dir: 'agents/ui_portal'
    id: 'build-ui-portal'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/ui-portal:latest'
    ]
    id: 'push-ui-portal'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ui-portal-service'
      - '--image'
      - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/ui-portal:latest'
      - '--service-account=${_SA_EMAIL}'
      - '--allow-unauthenticated'
      - '--region=${_GCP_REGION}'
      - '--platform=managed'
      - '--set-env-vars=GCP_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_PROJECT=${PROJECT_ID},RAW_DATA_BUCKET=${_RAW_DATA_BUCKET},ANALYZED_DATA_BUCKET=${_ANALYZED_DATA_BUCKET},ORCHESTRATION_TOPIC_ID=${_ORCHESTRATION_TOPIC_ID}'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--timeout=300s'
      - '--update-env-vars=GCP_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'
    id: 'deploy-ui-portal'

# Images to be pushed to Artifact Registry
images:
  - '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/ui-portal:latest'

# Timeout for the build (in seconds)
timeout: 1800s
